### ISSUE TITLE
Error: The task includes an option with an undefined variable.The error was: 'airflow_group' is undefined

### ISSUE THREAD

**Issue by sivasaiganesh08** [idealista/airflow-role#102]
I tried to install by following the instruction but getting this error. Moved the files from default -> main to default cleared the issue but getting undefined variable "airflow_dags_folder"
![err2](https://user-images.githubusercontent.com/45296961/117899014-dffaad80-b2e3-11eb-847a-1e8053d54efa.PNG)
![eer1](https://user-images.githubusercontent.com/45296961/117899016-e12bda80-b2e3-11eb-9b85-4c9a2abbcb5a.PNG)

**Comment by ultraheroe** [comment]
Hello @sivasaiganesh08 , please next time remember to fill the template we are providing for questions, bugs, etc

I don't understand well what are your errors, please, can you provide more details and information about? what version of the airflow-role are you running?
It seems to me that you have modified incorrectly some vars, the `airflow_skeleton_paths`, then maybe `airflow_dags_folder`

By default the `airflow_dags_folder` looks like [this](https://github.com/idealista/airflow-role/blob/master/defaults/main/airflow-cfg.yml#L5). Please check that you have set correctly your [airflow_app_home](https://github.com/idealista/airflow-role/blob/master/defaults/main/main.yml#L182)  that additionally depends of what you set on your [airflow_app_name](https://github.com/idealista/airflow-role/blob/master/defaults/main/main.yml#L3)

By the way I will suggest you to check folder permissions for the default skeleton var paths or the paths you have set.

Thanks,
David.
