### ISSUE TITLE
[BUG] template gunicorn-logrotate.j2

### ISSUE THREAD

**Issue by ginolegigot** [idealista/airflow-role#110]
Hello!
I'm using a part of your great project!
I have noticed a potential issue inside the template located in templates/gunicorn-logrotate.j2.
On the master branch, it's currently written in this way:
```jinja
{{ airflow_logs_folder }}/gunicorn-*.log {
    daily
    missingok
    rotate 7
    size 500M
    compress
    notifempty
    create 644 {{ airflow_user }} {{ airflow_group }}
    sharedscripts
    postrotate
        [ -f {{ airflow_pidfile_folder }}-webserver/webserver.pid ] && kill -USR1 `cat {{ airflow_pidfile_folder }}-webserver/webserver.pid`
    endscript
}
```
My issue concerns this code piece at the line before the last
```jinja
 kill -USR1 `cat {{ airflow_pidfile_folder }}/webserver.pid`
```
I think it needs an "-webserver" right after "{{ airflow_pidfile_folder }}" as it is written at the beginning of the line. Otherwise the logrotate script will fail.

Thanks for your time!

PS: I tried to push a PR but PR access seems to be forbidden for non-contributors

**Comment by vicsufer** [comment]
Hi @ginolegigot, I'm glad you find our project useful and thanks for spotting this bug!

Regarding the pull request, members outside our organization can't contribute to our repositories directly, however you can [create a fork of the repository](https://docs.github.com/get-started/quickstart/fork-a-repo), work freely on it and then [submit a pull request to our repository from the fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) (I Hope you find the links useful). We are open to contributions from everyone and will be glad to review your proposed changes 😄

**Comment by ginolegigot** [comment]
Thank you @vicsufer, i'll check it out

**Comment by ginolegigot** [comment]
PR submitted !

**Comment by ginolegigot** [comment]
Fixed with https://github.com/idealista/airflow-role/pull/111
