### ISSUE TITLE
idealista.airflow-role was NOT installed successfully

### ISSUE THREAD

**Issue by somasundaramsekar** [idealista/airflow-role#27]
downloading role from https://github.com/idealista/airflow-role/archive/1.3.1.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found

Unable to download any version of airflow-role.

```
$ ansible --version
ansible 2.4.0.0
  config file = /media/asg-airflow-terraform/ansible/ansible.cfg
  configured module search path = [u'/home/osboxes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

**Comment by juanriaza** [comment]
Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue?

**Comment by jnogol** [comment]
Closing the issue because of inactivity
