### ISSUE TITLE
Unable to install more than one Airflow Extra Package

### ISSUE THREAD

**Issue by AdriMarteau** [idealista/airflow-role#50]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
When specifying more than 1 airflow extra package, the task `Airflow | Installing Airflow Extra Packages` fails with error:
```
(item=['apache-airflow[celery]', 'apache-airflow[postgres]']) => {"changed": false, "item": ["apache-airflow[celery]", "apache-airflow[postgres]"], "msg": "'version' argument is ambiguous when installing multiple package distributions. Please specify version restrictions next to each package in 'name' argument."}
```
### Steps to Reproduce

1. Set in a vars file
```
airflow_version: 1.10.0
airflow_extra_packages: [celery,postgres]
```
2. Deploy Airflow using the role

**Expected behavior:** deployment to work

**Actual behavior:** deployment fails

**Reproduces how often:** Everytime

### Versions

1.7.2

### Additional Information
This also generate a warning:
```
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: "apache-airflow[{{ item }}]"`, please use `name: '{{
airflow_extra_packages }}'` and remove the loop. This feature will be removed in version 2.11.
```

**Comment by AdriMarteau** [comment]
not that it was intended but setting (without brackets): `airflow_extra_packages: celery,postgres` seems to work but the warning remains

**Comment by jnogol** [comment]
Hi @AdriMarteau 

Which Ansible version are you using?

**Comment by jnogol** [comment]
Thing is more delicate than I expected. Technically, [all members of a list are lines beginning at the same indentation level starting with a "- " (a dash and a space):](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html#yaml-basics) so we will specify the format in the defaults file and make a comma-separated list for Ansible versions greater than 2.7:

`"apache-airflow[{{ airflow_extra_packages | join(', ') }}]"`

This way, the role will have a backwards compatibility and will be able to use with Ansible 2.11
