### ISSUE TITLE
Add python 3.8 and create virtual env to install airflow

### ISSUE THREAD

**Issue by lorientedev** [idealista/airflow-role#66]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

To guarantee support and improve performance of actual and future versions of airflow I propose add python 3.8 and use virtualenv to prevent modify system python.

**Expected behavior:** Airflow will run with python 3.8 and virtualenv 

**Actual behavior:** Airflow runs with system python version.

### Versions

1.8.0

**Comment by vicsufer** [comment]
I thought it was a PR, my bad.
